### ISSUE TITLE
Website doesn't work or is down?

### ISSUE THREAD

**Issue by MattL-NZ** [themesberg/flowbite-angular#1]
**Describe the bug**
Unable to access the website: https://flowbite-angular.com/
Is this website currently down or still in development?

**Comment by Yochyo** [comment]
If I had to guess, [themesberg.github.io/flowbite-angular/](https://themesberg.github.io/flowbite-angular/) is the currently used website

**Comment by xiaolin911211** [comment]
@Yochyo  This new website does not have much components.

**Comment by Yochyo** [comment]
It was the only official documentation when I checked. I hope there is a complete one soon.

**Comment by boskiv** [comment]
Website works
