### ISSUE TITLE
FLowbite Components not working initially in Angular

### ISSUE THREAD

**Issue by Shalil-j** [themesberg/flowbite-angular#17]
I'm having masterLayout with **router-Outler**. In the master layout, I'm having a sidebar and navbar, on the sideBar i'm having multiple links to components, and all the components have some Flowbite components, but when I redirect to any particular page inside the master layout the components like a modal, accordion, dropdown not working initially, but if I reload that same page the components start working fine. Even I use the git repo of angular pre-installed with flowbite the issue still remains the same, and even if put the modal component which is in the git repo under route-outlet of the master layout it still not working. but the components like the dropdown, and navbar used in the main-layout work fine without any reload.  pls help me out I can't resolve this issue

**To Reproduce**
1. Go to 'pages with flowbite component inside router-outlet of master layout
2. Click on 'modal button'

**Expected behavior**
open modal,accordion should work fine without reloading the page manually

**Screenshots**
![WebApp](https://github.com/themesberg/flowbite-angular/assets/56194185/34c3e357-e352-4d25-a154-c94cb1b0f78d)

this is package.json
![image](https://github.com/themesberg/flowbite-angular/assets/56194185/f9d23773-d1ce-4a55-a579-9378f4b0e542)

this is the routing file
![image](https://github.com/themesberg/flowbite-angular/assets/56194185/28a4d5f1-6b65-4cf1-b8ad-27afb0b79e27)

and this is my master layout
![image](https://github.com/themesberg/flowbite-angular/assets/56194185/990566ad-53e9-476c-ad38-c80ad065de3f)

pls help me out, I'm counting on you
thank you

**Comment by OcrenSys** [comment]
I am currently using Angular v17 and I have the same problem, unfortunately I have not found any solution for this problem. Can someone help us to solve it.

**Comment by Klemenko** [comment]
So a quick fix for this problem is to call "initFlowbite" every time that the route changes.
More info here https://flowbite.com/docs/getting-started/javascript/#init-functions

**Comment by ayoubkhial** [comment]
I was wondering if there have been any updates on this issue. Currently, I'm using the workaround of initializing Flowbite on each component to mitigate the problem. It would be great to know if there's a more permanent solution on the horizon.

In my app.component.ts, I'm utilizing Angular's router events to reinitialize Flowbite whenever a navigation event ends. This ensures that Flowbite is correctly initialized for each component as users navigate through the application:
```js
// app.component.ts
ngOnInit() {
  this.router.events.subscribe((event) => {
    if (event instanceof NavigationEnd) {
      initFlowbite();
    }
  });
}
```

**Comment by MikaelFields** [comment]
this is not a solution: It seems to be possible to fix using route navigation events BUT if you reload the page sometimes loads the components correctly sometimes the load already broken, I hope there is a true solution for this. I'm using Angular 17 and SSR btw.

**Comment by SeijiV13** [comment]
in my case i need to add a timeout on the initflowbite() just to wait for the components to be initialized (might be helpful to others)
`  this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        setTimeout(() => {
          initFlowbite();
        })
      }
   });`

**Comment by SeijiV13** [comment]
in my case i need to add setTimeout on initFlowBite() (might be helpful to others)
```typescript
// app.component.ts
ngOnInit() {
  this.router.events.subscribe((event) => {
    if (event instanceof NavigationEnd) {
     setTimeout(() => {  initFlowbite();})
    }
  });
}
```

**Comment by ajdaling** [comment]
Same issue on Angular 18. Have to call initFlowbite() on every component, even children. Interestingly, Flowbite worked until I added an Auth Guard, but any route protected by a guard requires initFlowbite. Calling it in app.component does not work for all child components, even if I do it on every route change as previously suggested.

**Comment by timrasche** [comment]
Completed? Why? That is your solution to call init on every route change event?

**Comment by Andreibv** [comment]
On Angular 19 still not working, but using the solution of @ayoubkhial this work perfectly
