### ISSUE TITLE
Decay error when executing 'npm i flowbite-angular'. Angular-cli version 16.2.8.

### ISSUE THREAD

**Issue by dev-garcia** [themesberg/flowbite-angular#20]
**Describe the bug**
Decay error when executing 'npm i flowbite-angular'. Angular-cli version 16.2.8.

**Additional context**
In the updated version of Angular we are having an error when installing flowbite, preventing us from using components that use flowbite tags.

**Comment by MGREMY** [comment]
Hey @dev-garcia
As I said [here](https://github.com/themesberg/flowbite-angular/discussions/19), the repo is getting a big refacto PR [here](https://github.com/themesberg/flowbite-angular/pull/34)
However Angular 16 won't be supported, only Angular 17
