### ISSUE TITLE
Add ng17 support

### ISSUE THREAD

**Issue by GijsPampiermole** [themesberg/flowbite-angular#32]
**Is your feature request related to a problem? Please describe.**
I'm wanting to use flowbite for my latest project, but sadly there is no support yet for angular 17

**Describe the solution you'd like**
Please add support for angular 17

**Describe alternatives you've considered**
My alternative would be to drop flowbite for now and use tailwind to create custom components

**Additional context**
![image](https://github.com/themesberg/flowbite-angular/assets/69118714/9ea6a304-6297-49e2-9699-e3a98d8028d8)

**Comment by juanpabloguerra16** [comment]
any idea when this will be fixed?

**Comment by oscarviq** [comment]
I'm pretty sure this custom angular library is dead. I still use flowbite but I end up creating my own abstractions.

**Comment by MGREMY** [comment]
@GijsPampiermole @juanpabloguerra16 @oscarviq
The project is reviving :)
There's a big project cleanup (refacto + update to angular 17) on [this branch](https://github.com/themesberg/flowbite-angular/tree/refactor-components-properties)
The PR is created, just making sure everything is alright (if you mind you could look at it and tell me if there is something you think we have to change (except for form related and dropdown component, a rework is planned on it ;) ))

**Comment by MGREMY** [comment]
Hey
Finally, the beta version is out (https://www.npmjs.com/package/flowbite-angular/v/1.0.0-beta.1). This issue will be fixed in the next version deployment (1.0.0)

**Comment by MGREMY** [comment]
Hey !
The library is out on 1.0.0, on angular 18 !
