### ISSUE TITLE
Angular 18

### ISSUE THREAD

**Issue by quedicesebas** [themesberg/flowbite-angular#42]
How can I help to move to a release version for the current Angular version?

**Comment by MGREMY** [comment]
> How can I help to move to a release version for the current Angular version?

You can help me on the branch `rework_documentation_front`. There is a figma for the documentation, and we have plenty of work to do on components styling (like simplify it, make it more compete with more parameters per components)

**Comment by quedicesebas** [comment]
@MGREMY but that branch is outdated no? Where do we communicate? I think an issue is not the place

**Comment by MGREMY** [comment]
@quedicesebas you found the discors so.. on discord 😉

https://discord.com/invite/flowbite-902911619032576090

**Comment by MGREMY** [comment]
Hey
Finally, the beta version is out (https://www.npmjs.com/package/flowbite-angular/v/1.0.0-beta.1). This issue will be fixed in the next version deployment (1.0.0)

**Comment by MGREMY** [comment]
Hey, I'm closing this issue since the 1.0.0 is out and works under angular 18 !
