### ISSUE TITLE
Deployment of v0.0.3 failed

### ISSUE THREAD

**Issue by flodt** [themesberg/flowbite-angular#47]
**Describe the bug**
The version tagged with `v0.0.3` is not correctly deployed as an npm package.

**To Reproduce**
1. Go to [https://www.npmjs.com/package/flowbite-angular](https://www.npmjs.com/package/flowbite-angular)
2. Check newest version
3. Verify that only `v0.0.2` is correctly deployed

**Expected behavior**
`v0.0.3` is available as an npm package

**Screenshots**
![image](https://github.com/user-attachments/assets/032e115b-907d-44b4-94e4-3d653ef64d12)

**Comment by MGREMY** [comment]
Heyy
Sorry for the late response..
I already answered in [this message](https://github.com/themesberg/flowbite-angular/discussions/41#discussioncomment-10940989)
