### ISSUE TITLE
Upgrade to Nx & Angular LTS Versions

### ISSUE THREAD

**Issue by tomavic** [themesberg/flowbite-angular#63]
**Objective**

Use Latest Stable Versions of Nx, Angular and Node.js

According to [Nx and Angular Versions](https://nx.dev/nx-api/angular/documents/angular-nx-version-matrix) 

<img width="702" alt="Screenshot 2024-10-24 at 2 18 50 AM" src="https://github.com/user-attachments/assets/c47b0415-1488-489b-bdc4-7737faac7b64">

**Comment by MGREMY** [comment]
Just looked at nx and angular version
If we stick on the last lts angular version, then it's angular 17. Nx for angular 17 we can go on the latest lts so v19
Since the project is on angular 18 right now and Nx v19, we will need to do a downgrade of angular version

**Comment by MGREMY** [comment]
And depending on the angular version, we will need to update the typescript and node version (in CD/CI for example)
![image](https://github.com/user-attachments/assets/00125b5d-ac81-49fe-9e0a-7e998b57c23b)

**Comment by MGREMY** [comment]
Item created in the board : https://github.com/orgs/themesberg/projects/11?pane=issue&itemId=84626200
