### ISSUE TITLE
Prepare 1.0.0 from beta

### ISSUE THREAD

**Issue by MGREMY** [themesberg/flowbite-angular#75]
## Repo
- [x] Add PR template
- [x] Add issue template
- [x] Add feature request template

## Fix in doc itself
- [x] Add spacing for each example components

## Documentation

- [x] Code block background color
- [x] Found a solution for code block indentation in demo

### Navbar
- [x] Fix icon button color in documentation
- [x] Fix responsive behaviour
- [x] Fix search bar location
- [x] Add version on top right navbar

![image](https://github.com/user-attachments/assets/9aaf64a0-4019-428f-b35f-922a042a051c)

#### Breadcrumb
- [x] Link on BreadcrumbItem
#### Modal
- [x] Redirect link modal with form

### Accordion
- [x] Border

**Comment by omarsherief1** [comment]
I've been refreshing this page daily, excited to have this for Angular finally!

**Comment by MGREMY** [comment]
@omarsherief1 yeahhhh it's planed for this monady, need to test the last version offline and offside of the repository
There'll be a message on the discord server when the update will be out !
