### ISSUE TITLE
Could not resolve "@floating-ui/dom"

### ISSUE THREAD

**Issue by mruknowme** [themesberg/flowbite-angular#77]
With `nx` setup getting this error during build

```sh
[ERROR] Could not resolve "@floating-ui/dom"
      
          node_modules/flowbite-angular/fesm2022/flowbite-angular-dropdown.mjs:9:65:
            9 │ ...osition, offset, flip, shift, autoUpdate } from '@floating-ui/dom';
```

**Comment by MGREMY** [comment]
That's why we have to get rid of `@floating-ui`

Add this into your package.json
`"@floating-ui/dom": "1.2.6",`

**Comment by MGREMY** [comment]
It's temporary, this library need to go out since we can achieve the same result with TailwindCSS classes

**Comment by MGREMY** [comment]
Closing this issue since in the 1.1.0, `@floating-ui` is not a dependency anymore
Also you can remove ir from your package.json :)
