### ISSUE TITLE
Please update to NG15

### ISSUE THREAD

**Issue by weilinzung** [themesberg/flowbite-angular#9]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by QuarkAgency** [comment]
Would be great

**Comment by boskiv** [comment]
But it's already on 15 ?
`"@angular/core": "15.0.2",`

**Comment by QuarkAgency** [comment]
Yes just the npm package on registry that is still in v.0.01 : https://www.npmjs.com/package/flowbite-angular

**Comment by stehag** [comment]
How do i use this with A15?

**Comment by MGREMY** [comment]
Hey,
The new version of flowbite-angular will come soon. For now, the library is in beta (https://www.npmjs.com/package/flowbite-angular/v/1.0.0-beta.1).
Since we're using signals, It may be possible that the library won't work correctly for angular 15, but it will work for angular 16.

**Comment by MGREMY** [comment]
Hey !
The library is out on 1.0.0, on angular 18 !
